export const cityNameMapper = {
  Tehran: "تهران",
  Sanandaj: "سنندج",
  Sananndaj: "سنندج",
  Isfahan: "اصفهان",
  Mazandaran: "مازندران",
  Gilan: "گیلان",
  Kish: "کیش",
  Qeshm: "قشم",
  Shiraz: "شیراز",
  Mashhad: "مشهد",
  Tabriz: "تبریز",
  Yazd: "یزد",
  Kerman: "کرمان",
  Chabahar: "چابهار",
  Offroad: "آفرود طبیعت‌گردی",
  // خاورمیانه و همسایگان
  Istanbul: "استانبول",
  Dubai: "دبی",
  Tbilisi: "تفلیس",
  Yerevan: "ایروان",
  Baku: "باکو",
  Muscat: "مسقط",
  Antalya: "آنتالیا",
  Sulaymaniyah: "سلیمانیه",
  Hewler: "اربیل (هولر)",
  Doha: "دوحه",
  // اروپا
  Paris: "پاریس",
  Madrid: "مادرید",
  Italy: "رم و ونیز",
  Zurich: "زوریخ",
  Moscow: "مسکو",
  London: "لندن",
  Barcelona: "بارسلونا",
  Amsterdam: "آمستردام",
  Athens: "آتن",
  // آسیا و مناطق استوایی
  KualaLumpur: "کوالالامپور",
  Phuket: "پوکت",
  Maldives: "مالدیو",
  Goa: "گوا",
  Tokyo: "توکیو",
  Seoul: "سئول",
  Bali: "بالی",
  Singapore: "سنگاپور",
  Bangkok: "بانکوک",
  Beijing: "پکن",
  // قاره‌های دیگر
  Rio: "ریودوژانیرو",
  CapeTown: "کیپ‌تاون",
};
