import localFont from "next/font/local";

import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { cookies } from "next/headers";
import ToastProvider from "@/components/utils/ToastProvider";

const customFont = localFont({
  src: [
    {
      path: "./fonts/YekanBakhMedium.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/YekanBakhBold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/YekanBakhHeavy.woff",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-custom",
  display: "swap",
});

export const metadata = {
  title: "Torino",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const accessToken = cookieStore.get("accessToken")?.value;
  const isLoggedIn = !!accessToken;

  const userDataCookie = cookieStore.get("userData")?.value;
  let userMobile = "پروفایل کاربری";

  if (userDataCookie) {
    try {
      const userObj = JSON.parse(userDataCookie);
      userMobile = userObj.firstName || userObj.mobile || "پروفایل";
    } catch (error) {
      console.error("خطا در پارس کردن دیتای کاربر");
    }
  }

  return (
    <html
      lang="fa"
      dir="rtl"
      className={`${customFont.variable} h-full antialiased `}
      suppressHydrationWarning
    >
      <body
        className="flex flex-col min-h-screen bg-gray-50 font-sans"
        suppressHydrationWarning
      >
        <ToastProvider />
        <Header isLoggedIn={isLoggedIn} userMobile={userMobile} />
        <main className="grow bg-gray-50">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
