import localFont from "next/font/local";

import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const customFont = localFont({
  src: [
    {
      path: "./fonts/YekanBakhMedium.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/YekanBakhBold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/YekanBakhHeavy.woff",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-custom",
  display: "swap",
});

export const metadata = {
  title: "Torino",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={`${customFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
